name: Push to dockerhub

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: chacoll/twitch-chat-replay:latest

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.15.0
        
      - name: Build image
        run: |
          npm install
          npm run build
          docker build . --tag $IMAGE_NAME

      - name: Push to DockerHub
        run: |
          docker login --username chacoll --password "${{ secrets.DOCKER_HUB_PASSWORD }}"
          docker push $IMAGE_NAME

      - name: Restart app on server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > privkey.key
          chmod 400 privkey.key
          ssh -o StrictHostKeyChecking=no -i privkey.key charlie@clickityclack.co.uk "~/workspace/twitch-chat-replay/restart-server.sh &>/dev/null"
          rm privkey.key
